version: '3.9'

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "443:443"
    volumes:
      - ./output:/etc/nginx/certs:ro     # Zertifikate einbinden
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Konfiguration
    networks:
      - pki_net

networks:
  pki_net:
    external: true
